# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: twm_dev
  host: 127.0.0.1
  username: twm

test:
  adapter: postgresql
  database: twm_test
  host: 127.0.0.1
  username: twm

production:
  adapter: postgresql
  database: twm_production
  username: twm
  password: twm
  host: /tmp
  port: 5432
